### ISSUE TITLE
Follow PEP8 standards

### ISSUE THREAD

**Issue by malmans2** [PFPE/shipgrav#12]
Especially if you encourage external contributions, I suggest following [PEP8](https://peps.python.org/pep-0008/) standards as closely as possible. There are many linters and formatters that can help easily check and enforce these standards. For example, I recommend running:

- [isort](https://pycqa.github.io/isort/): sort imports
- [black](https://github.com/psf/black): code formatter
- [flake8](https://flake8.pycqa.org/en/latest/): enforce the PEP8 style guide

openjournals/joss-reviews#7358

**Comment by hfmark** [comment]
I did run `autopep8` on everything, but I guess that only covers some aspects. a4c8a60f3e0dc8a26aa3da9abadba8c314dbec86 and 6eefc086f82d4f0c92168429e5df80efe1363b25 are running `isort` and some corrections from `flake8`. Personally I don't love the "blackened" style - I find it less readable - but if it's really important I can add it.

**Comment by malmans2** [comment]
Nowadays, it's hard to find open-source software that doesn't use Black or Ruff. In my opinion, this improves readability, as it's the standard most developers are familiar with. However, code formatting is not a requirement for JOSS, so it's not mandatory.
