### ISSUE TITLE
Mention how to install optional dependencies

### ISSUE THREAD

**Issue by malmans2** [PFPE/shipgrav#14]
I suggest explicitly mentioning in the documentation how to install the optional dependencies required to run the example scripts.

E.g., `pip install "shipgrav[examples]"`

openjournals/joss-reviews#7358

**Comment by hfmark** [comment]
Sorry about the slightly messy commits, but this is done.

**Comment by malmans2** [comment]
Nice, thanks!
I noticed from the commits that you're suggesting the conda installation and listing dependencies to install. Have you thought about releasing `shipgrav` on `conda-forge` as well? This way, users could simply run `conda install -c conda-forge shipgrav`. Setting up a `conda-forge` recipe is straightforward, and once it's set up, a bot manages most updates for you.

**Comment by hfmark** [comment]
I have thought about it, and it's on my list of things to do eventually!
