### ISSUE TITLE
Tests fail under python 3.13

### ISSUE THREAD

**Issue by andreww** [PFPE/shipgrav#2]
I tried running the tests as part of the JOSS review: https://github.com/openjournals/joss-reviews/issues/7358. I see errors like this when trying to run the test cases under python 3.13 (i.e. the version currently installed by default by conda).

```
________________ ERROR collecting shipgrav/tests/test_grav_data.py _________________
ImportError while importing test module '/Users/andreww/Code/shipgrav/shipgrav/shipgrav/tests/test_grav_data.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../miniforge3/envs/shipgrav/lib/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/__init__.py:5: in <module>
    from pkg_resources import resource_filename
E   ModuleNotFoundError: No module named 'pkg_resources'
```

I think this is basically the same as the error described at https://github.com/mu-editor/mu/issues/2485 - I think the links in that issue describe the fixes.

**Comment by hfmark** [comment]
Now works on 3.13 (and still fine for 3.9, 3.10, 3.11)
