### ISSUE TITLE
Test automation

### ISSUE THREAD

**Issue by andreww** [PFPE/shipgrav#3]
This is also part of the JOSS review: https://github.com/openjournals/joss-reviews/issues/7358.

It would be a really good idea if the tests were set up to run in an automated manner (on multiple python versions) as and when the code is changed. One way to do this would be to plug the tests into github actions with the appropriate triggers. Some documentation can be found at: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python - and if it's useful I can probably find a relevant example case without too much effort.

**Comment by hfmark** [comment]
I had them set with a cron job; that's still there, but now they run on push as well. I also cleaned up the os matrix and added 3.13, which passes :slightly_smiling_face:
